### ISSUE TITLE
What is the algorithm used to generate MU datasets?

### ISSUE THREAD

**Issue by UnixJunkie** [jwxia2014/MUBD-DecoyMaker2.0#2]
Is it this one?
Rohrer, S. G., & Baumann, K. (2009). Maximum unbiased validation (MUV) data sets for virtual screening based on PubChem bioactivity data. Journal of chemical information and modeling, 49(2), 169-184.

**Comment by jwxia2014** [comment]
Thanks for your question. 
The tool is based on our previously published algorithm. Please refer to: 
Xia, J.; Jin, H.; Liu, Z.; Zhang, L.; Wang, X.S., An unbiased method to build benchmarking sets for ligand-based virtual screening and its application to GPCRs. J. Chem. Inf. Model., 2014, 54 (5): 1433-1450.

**Comment by UnixJunkie** [comment]
Ok, I was looking for an open-source implementation of the 2009 paper.
